server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  types {
    application/font-woff woff;
    application/font-woff2 woff2;
    application/x-font-ttf ttf;
    application/x-font-otf otf;
    application/x-font-truetype ttf;
    font/opentype otf;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /assets/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
    add_header Access-Control-Allow-Origin "*";
  }
}

