services:
  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_bookstore
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  recommendation-service:
    build:
      context: ./recommendation-service
    container_name: recommendation-service
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: db_bookstore
      DB_USER: app
      DB_PASSWORD: app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  backend:
    image: morex3/bookstore-backend:latest
    container_name: backend-dev
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_bookstore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app

volumes:
  mysql_data:

#docker build -t morex3/bookstore-backend:latest ./backend/bookstore
#docker push morex3/bookstore-backend:latest


#docker compose down -v
#docker compose up --build