server:
  port: 8080
  tomcat:
    max-parameter-count: 1000
    max-part-count: 100 #Tăng số lượng part tải lên
  servlet:
    context-path: /bookstore

cloudinary:
    cloud-name: "duqhdj1ff"
    api-key: "346155614337958"
    api-secret: "YezmWlvHW0dkAs6x4Lodf3jH1dQ"
spring:
  servlet: # Chuyển servlet vào bên dưới spring
    multipart:
      enabled: true
      location: /tmp/spring-uploads
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    url: "jdbc:mysql://localhost:3307/db_bookstore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh"
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
