server:
  port: 8080
  tomcat:
    max-parameter-count: 1000
    max-part-count: 100 #Tăng số lượng part tải lên
  servlet:
    context-path: /bookstore

cloudinary:
    cloud-name: "duqhdj1ff"
    api-key: "346155614337958"
    api-secret: "YezmWlvHW0dkAs6x4Lodf3jH1dQ"
spring:
  servlet:
    multipart:
      enabled: true
      location: /tmp/spring-uploads
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    url: "jdbc:mysql://localhost:3306/db_bookstore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh"
    username: root
    password: "153246789"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
vnpay:
  tmn-code: "F4VJN4XW"         # Mã website tại VNPay
  hash-secret: "GH961WQ2EHQ3COP1TJ93K0F0OJGBIUIM"   # Chuỗi bí mật để ký
  url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "http://localhost:8080/bookstore/api/v1/payments/callback"
jwt:
  signerKey: "da71bbd42f53166b283fae318f1ab668822d1980543618f423d4b6d63ce9d5fb"
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # in second