-- MySQL Script generated by MySQL Workbench
-- Tue Apr  7 22:26:29 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_bookstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_bookstore` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_bookstore` ;

-- -----------------------------------------------------
-- Table `db_bookstore`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `role_name` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`users` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `dob` DATETIME(6) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `gender` VARCHAR(255) NULL DEFAULT NULL,
  `is_change_account` BIT(1) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `point` BIGINT NOT NULL,
  `status` BIT(1) NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `role_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `FKp56c1712k691lhsyewcssf40f` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKp56c1712k691lhsyewcssf40f`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_bookstore`.`roles` (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`addresses` (
  `address_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `customer_name` VARCHAR(255) NULL DEFAULT NULL,
  `customer_phone` VARCHAR(255) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `detail_address` VARCHAR(255) NULL DEFAULT NULL,
  `district` VARCHAR(255) NULL DEFAULT NULL,
  `is_default` BIT(1) NOT NULL,
  `province` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `ward` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `FK1fa36y2oqhao3wgg2rw1pi459` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK1fa36y2oqhao3wgg2rw1pi459`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_bookstore`.`users` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`authors` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(255) NOT NULL,
  `author_name` VARCHAR(200) NOT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`author_id`),
  UNIQUE INDEX `UKpl4h214wgo83wuxp2g2ud0gwm` (`alias` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`publishers` (
  `publisher_id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `publisher_name` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`publisher_id`),
  UNIQUE INDEX `UK86rbulstali2f0pdguulfyn40` (`publisher_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`books` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `avg_rating` FLOAT NOT NULL,
  `cover_image_url` VARCHAR(255) NULL DEFAULT NULL,
  `cover_type` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `is_active` BIT(1) NOT NULL,
  `isbn` VARCHAR(255) NULL DEFAULT NULL,
  `language` VARCHAR(255) NULL DEFAULT NULL,
  `page_count` INT NOT NULL,
  `price` DECIMAL(38,2) NULL DEFAULT NULL,
  `sale_percent` INT NOT NULL,
  `stock_quantity` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `publisher_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`book_id`),
  UNIQUE INDEX `UKkibbepcitr0a3cpk3rfr7nihn` (`isbn` ASC) VISIBLE,
  INDEX `FKayy5edfrqnegqj3882nce6qo8` (`publisher_id` ASC) VISIBLE,
  CONSTRAINT `FKayy5edfrqnegqj3882nce6qo8`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `db_bookstore`.`publishers` (`publisher_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`book_author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`book_author` (
  `book_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `author_id`),
  INDEX `FKro54jqpth9cqm1899dnuu9lqg` (`author_id` ASC) VISIBLE,
  CONSTRAINT `FK91ierknt446aaqnjl4uxjyls3`
    FOREIGN KEY (`book_id`)
    REFERENCES `db_bookstore`.`books` (`book_id`),
  CONSTRAINT `FKro54jqpth9cqm1899dnuu9lqg`
    FOREIGN KEY (`author_id`)
    REFERENCES `db_bookstore`.`authors` (`author_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`carts` (
  `cart_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`cart_id`),
  UNIQUE INDEX `UK64t7ox312pqal3p7fg9o503c2` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKb5o626f86h46m4s7ms6ginnop`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_bookstore`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`book_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`book_cart` (
  `book_cart_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `quantity` INT NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `book_id` INT NULL DEFAULT NULL,
  `cart_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`book_cart_id`),
  INDEX `FK13d0pmxfe82vwbuckfqry2792` (`book_id` ASC) VISIBLE,
  INDEX `FKhsaedbd79d2wf7akv09svuuf3` (`cart_id` ASC) VISIBLE,
  CONSTRAINT `FK13d0pmxfe82vwbuckfqry2792`
    FOREIGN KEY (`book_id`)
    REFERENCES `db_bookstore`.`books` (`book_id`),
  CONSTRAINT `FKhsaedbd79d2wf7akv09svuuf3`
    FOREIGN KEY (`cart_id`)
    REFERENCES `db_bookstore`.`carts` (`cart_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`categories` (
  `category_id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `parent_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `FKsaok720gsu4u2wrgbk10b5n8d` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `FKsaok720gsu4u2wrgbk10b5n8d`
    FOREIGN KEY (`parent_id`)
    REFERENCES `db_bookstore`.`categories` (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`book_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`book_category` (
  `category_id` BIGINT NOT NULL,
  `book_id` INT NOT NULL,
  INDEX `FK7k0c5mr0rx89i8jy5ges23jpe` (`book_id` ASC) VISIBLE,
  INDEX `FKiwvwb2bwuvg0017hh8kg5e8g1` (`category_id` ASC) VISIBLE,
  CONSTRAINT `FK7k0c5mr0rx89i8jy5ges23jpe`
    FOREIGN KEY (`book_id`)
    REFERENCES `db_bookstore`.`books` (`book_id`),
  CONSTRAINT `FKiwvwb2bwuvg0017hh8kg5e8g1`
    FOREIGN KEY (`category_id`)
    REFERENCES `db_bookstore`.`categories` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`book_imgs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`book_imgs` (
  `book_img_id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `img_url` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `book_book_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`book_img_id`),
  INDEX `FKe39xqehsn43ym9as5cnfinvf8` (`book_book_id` ASC) VISIBLE,
  CONSTRAINT `FKe39xqehsn43ym9as5cnfinvf8`
    FOREIGN KEY (`book_book_id`)
    REFERENCES `db_bookstore`.`books` (`book_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`vouchers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`vouchers` (
  `voucher_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `discount_value` DECIMAL(19,2) NULL DEFAULT NULL,
  `end_date` DATETIME(6) NULL DEFAULT NULL,
  `is_active` BIT(1) NULL DEFAULT NULL,
  `limit_per_user` INT NULL DEFAULT NULL,
  `max_discount_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `min_order_value` DECIMAL(19,2) NULL DEFAULT NULL,
  `min_point` BIGINT NULL DEFAULT NULL,
  `start_date` DATETIME(6) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `total_limit` INT NULL DEFAULT NULL,
  `type` ENUM('FIXED', 'PERCENTAGE') NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `used_count` INT NULL DEFAULT NULL,
  `voucher_code` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`voucher_id`),
  UNIQUE INDEX `UKhvqsc8qffpt5okjmyot3a4b77` (`voucher_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`orders` (
  `order_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `total_amount` DECIMAL(38,2) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `vat_amount` DECIMAL(12,2) NULL DEFAULT NULL,
  `vat_rate` DECIMAL(5,2) NOT NULL,
  `customer_id` BIGINT NULL DEFAULT NULL,
  `staff_id` BIGINT NULL DEFAULT NULL,
  `voucher_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `UK4gw7a2rkjix1kost1mk42dcc6` (`voucher_id` ASC) VISIBLE,
  INDEX `FKsjfs85qf6vmcurlx43cnc16gy` (`customer_id` ASC) VISIBLE,
  INDEX `FKe979ux6efhhi6ph712agy4bit` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `FKdimvsocblb17f45ikjr6xn1wj`
    FOREIGN KEY (`voucher_id`)
    REFERENCES `db_bookstore`.`vouchers` (`voucher_id`),
  CONSTRAINT `FKe979ux6efhhi6ph712agy4bit`
    FOREIGN KEY (`staff_id`)
    REFERENCES `db_bookstore`.`users` (`user_id`),
  CONSTRAINT `FKsjfs85qf6vmcurlx43cnc16gy`
    FOREIGN KEY (`customer_id`)
    REFERENCES `db_bookstore`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`book_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`book_order` (
  `book_order_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `quantity` INT NOT NULL,
  `unit` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `book_id` INT NULL DEFAULT NULL,
  `order_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`book_order_id`),
  INDEX `FKaqslrmby03dyqpqk3qyqdseil` (`book_id` ASC) VISIBLE,
  INDEX `FK51fe92cu6xccyugt0w481o8ay` (`order_id` ASC) VISIBLE,
  CONSTRAINT `FK51fe92cu6xccyugt0w481o8ay`
    FOREIGN KEY (`order_id`)
    REFERENCES `db_bookstore`.`orders` (`order_id`),
  CONSTRAINT `FKaqslrmby03dyqpqk3qyqdseil`
    FOREIGN KEY (`book_id`)
    REFERENCES `db_bookstore`.`books` (`book_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`interact_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`interact_events` (
  `interact_event_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `event_time` DATETIME(6) NULL DEFAULT NULL,
  `event_type` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `value` INT NOT NULL,
  `book_id` INT NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`interact_event_id`),
  INDEX `FKto5p83hy26022gxl77bsmmbwe` (`book_id` ASC) VISIBLE,
  INDEX `FKd4gfqjqri79q2qjyncj8fr3pe` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKd4gfqjqri79q2qjyncj8fr3pe`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_bookstore`.`users` (`user_id`),
  CONSTRAINT `FKto5p83hy26022gxl77bsmmbwe`
    FOREIGN KEY (`book_id`)
    REFERENCES `db_bookstore`.`books` (`book_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`invalidated_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`invalidated_token` (
  `id` VARCHAR(255) NOT NULL,
  `expiry_time` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`payments` (
  `payment_id` BIGINT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(38,2) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `method` ENUM('COD', 'MOMO', 'VNPAY', 'ZALOPAY') NULL DEFAULT NULL,
  `paid_at` DATETIME(6) NULL DEFAULT NULL,
  `status` ENUM('CANCELLED', 'FAILED', 'PENDING', 'SUCCESS') NULL DEFAULT NULL,
  `transaction_id` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `order_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  UNIQUE INDEX `UK8vo36cen604as7etdfwmyjsxt` (`order_id` ASC) VISIBLE,
  CONSTRAINT `FK81gagumt0r8y3rmudcgpbk42l`
    FOREIGN KEY (`order_id`)
    REFERENCES `db_bookstore`.`orders` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`permissions` (
  `permission_id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `permission_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`permission_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`reviews` (
  `review_id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `rating` INT NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `book_id` INT NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `FK6a9k6xvev80se5rreqvuqr7f9` (`book_id` ASC) VISIBLE,
  INDEX `FKcgy7qjc1r99dp117y9en6lxye` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK6a9k6xvev80se5rreqvuqr7f9`
    FOREIGN KEY (`book_id`)
    REFERENCES `db_bookstore`.`books` (`book_id`),
  CONSTRAINT `FKcgy7qjc1r99dp117y9en6lxye`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_bookstore`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`role_permission` (
  `role_id` INT NOT NULL,
  `permission_id` BIGINT NOT NULL,
  INDEX `FK2xn8qv4vw30i04xdxrpvn3bdi` (`permission_id` ASC) VISIBLE,
  INDEX `FKtfgq8q9blrp0pt1pvggyli3v9` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FK2xn8qv4vw30i04xdxrpvn3bdi`
    FOREIGN KEY (`permission_id`)
    REFERENCES `db_bookstore`.`permissions` (`permission_id`),
  CONSTRAINT `FKtfgq8q9blrp0pt1pvggyli3v9`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_bookstore`.`roles` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`shipments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`shipments` (
  `shipment_id` BIGINT NOT NULL AUTO_INCREMENT,
  `actual_delivery_date` DATETIME(6) NULL DEFAULT NULL,
  `carrier_name` VARCHAR(255) NULL DEFAULT NULL,
  `customer_name` VARCHAR(255) NULL DEFAULT NULL,
  `customer_phone` VARCHAR(255) NULL DEFAULT NULL,
  `detail_address` VARCHAR(255) NULL DEFAULT NULL,
  `district` VARCHAR(255) NULL DEFAULT NULL,
  `estimated_delivery_date` DATETIME(6) NULL DEFAULT NULL,
  `province` VARCHAR(255) NULL DEFAULT NULL,
  `status` INT NOT NULL,
  `tracking_number` VARCHAR(255) NULL DEFAULT NULL,
  `ward` VARCHAR(255) NULL DEFAULT NULL,
  `order_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`shipment_id`),
  UNIQUE INDEX `UKhrhy2yghr8dampg1jtecuekvp` (`order_id` ASC) VISIBLE,
  CONSTRAINT `FKrnt4wht95lxxplspltrg9681s`
    FOREIGN KEY (`order_id`)
    REFERENCES `db_bookstore`.`orders` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_bookstore`.`user_voucher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bookstore`.`user_voucher` (
  `user_id` BIGINT NOT NULL,
  `voucher_id` BIGINT NOT NULL,
  INDEX `FK6ovy02abqo70lq56slfatntmv` (`voucher_id` ASC) VISIBLE,
  INDEX `FKqbre9r4sb85kdd0q1d9fa8c9m` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK6ovy02abqo70lq56slfatntmv`
    FOREIGN KEY (`voucher_id`)
    REFERENCES `db_bookstore`.`vouchers` (`voucher_id`),
  CONSTRAINT `FKqbre9r4sb85kdd0q1d9fa8c9m`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_bookstore`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
